name: Release data_understand to PyPI

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Test or Prod PyPI?"
        required: true
        default: "Test"

jobs:
  release-data_understand:
    runs-on: ubuntu-latest
    steps:
      - name: fail if Test nor Prod
        if: ${{ ! (github.event.inputs.type == 'Test' || github.event.inputs.type == 'Prod') }}
        run: |
          echo "Only Test or Prod can be used."
          exit 1
      # build wheel
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: update and upgrade pip, setuptools, wheel, and twine
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
      - name: install requirements.txt for data_understand
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: pip freeze
        run: pip freeze

      - name: build wheel for data_understand
        run: python setup.py sdist bdist_wheel

      # run tests before publishing to PyPI

      - name: install data_understand wheel locally
        run: find ./dist/ -name '*.whl' -exec pip install {} \;

      - name: run data_understand tests
        run: pytest ./tests/

      # publish to PyPI
      - name: Publish data_understand package to PyPI
        if: ${{ github.event.inputs.type == 'Prod' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_DATA_UNDERSTAND }}
          packages_dir: ./dist/
